l#-------------------------------
# General Site Settings
title: BetterBetter.Life
logo: logo.svg # You can add own logo.
description: BetterBetter.Life dedicated to helping people achieve better mental health.


#-------------------------------
# Author Settings
author:
  name: BetterBetter.Life
  image: 01.jpg
  say-hello: Welcome to <strong>BetterBetter.Life</strong>
  bio:  Its a personal studio dedicated to helping people achieve better mental health.


#-------------------------------
# Contact links
twitter: https://twitter.com/ # Add your Twitter handle
#facebook: https://facebook.com/ # Add your Facebook handle
#dribbble: https://dribbble.com/ # Add your Dribbble handle
#instagram: https://instagram.com/ # Add your Instagram handle
#pinterest: https://pinterest.com/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: betterbetterlife # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: G-LV8978QF46 # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
